/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminEntitiesRouteImport } from './routes/admin.entities'
import { Route as AdminEntitiesIdRouteImport } from './routes/admin.entities.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntitiesRoute = AdminEntitiesRouteImport.update({
  id: '/admin/entities',
  path: '/admin/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntitiesIdRoute = AdminEntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEntitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/entities': typeof AdminEntitiesRouteWithChildren
  '/admin/entities/$id': typeof AdminEntitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/entities': typeof AdminEntitiesRouteWithChildren
  '/admin/entities/$id': typeof AdminEntitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/entities': typeof AdminEntitiesRouteWithChildren
  '/admin/entities/$id': typeof AdminEntitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/entities' | '/admin/entities/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/entities' | '/admin/entities/$id'
  id: '__root__' | '/' | '/admin/entities' | '/admin/entities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminEntitiesRoute: typeof AdminEntitiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entities': {
      id: '/admin/entities'
      path: '/admin/entities'
      fullPath: '/admin/entities'
      preLoaderRoute: typeof AdminEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entities/$id': {
      id: '/admin/entities/$id'
      path: '/$id'
      fullPath: '/admin/entities/$id'
      preLoaderRoute: typeof AdminEntitiesIdRouteImport
      parentRoute: typeof AdminEntitiesRoute
    }
  }
}

interface AdminEntitiesRouteChildren {
  AdminEntitiesIdRoute: typeof AdminEntitiesIdRoute
}

const AdminEntitiesRouteChildren: AdminEntitiesRouteChildren = {
  AdminEntitiesIdRoute: AdminEntitiesIdRoute,
}

const AdminEntitiesRouteWithChildren = AdminEntitiesRoute._addFileChildren(
  AdminEntitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminEntitiesRoute: AdminEntitiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
