/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameDataRouteImport } from './routes/game-data'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as CreateRouteImport } from './routes/create'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameDataIdRouteImport } from './routes/game-data_.$id'
import { Route as EntitiesIdRouteImport } from './routes/entities_.$id'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const GameDataRoute = GameDataRouteImport.update({
  id: '/game-data',
  path: '/game-data',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDataIdRoute = GameDataIdRouteImport.update({
  id: '/game-data_/$id',
  path: '/game-data/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIdRoute = EntitiesIdRouteImport.update({
  id: '/entities_/$id',
  path: '/entities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builds': typeof BuildsRoute
  '/create': typeof CreateRoute
  '/entities': typeof EntitiesRoute
  '/game-data': typeof GameDataRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/game-data/$id': typeof GameDataIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builds': typeof BuildsRoute
  '/create': typeof CreateRoute
  '/entities': typeof EntitiesRoute
  '/game-data': typeof GameDataRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/game-data/$id': typeof GameDataIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builds': typeof BuildsRoute
  '/create': typeof CreateRoute
  '/entities': typeof EntitiesRoute
  '/game-data': typeof GameDataRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/entities_/$id': typeof EntitiesIdRoute
  '/game-data_/$id': typeof GameDataIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/builds'
    | '/create'
    | '/entities'
    | '/game-data'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/entities/$id'
    | '/game-data/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/builds'
    | '/create'
    | '/entities'
    | '/game-data'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/entities/$id'
    | '/game-data/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/builds'
    | '/create'
    | '/entities'
    | '/game-data'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/entities_/$id'
    | '/game-data_/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildsRoute: typeof BuildsRoute
  CreateRoute: typeof CreateRoute
  EntitiesRoute: typeof EntitiesRoute
  GameDataRoute: typeof GameDataRoute
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  EntitiesIdRoute: typeof EntitiesIdRoute
  GameDataIdRoute: typeof GameDataIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game-data': {
      id: '/game-data'
      path: '/game-data'
      fullPath: '/game-data'
      preLoaderRoute: typeof GameDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-data_/$id': {
      id: '/game-data_/$id'
      path: '/game-data/$id'
      fullPath: '/game-data/$id'
      preLoaderRoute: typeof GameDataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities_/$id': {
      id: '/entities_/$id'
      path: '/entities/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof EntitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildsRoute: BuildsRoute,
  CreateRoute: CreateRoute,
  EntitiesRoute: EntitiesRoute,
  GameDataRoute: GameDataRoute,
  AccountAccountViewRoute: AccountAccountViewRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  EntitiesIdRoute: EntitiesIdRoute,
  GameDataIdRoute: GameDataIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
